#########################################
# Configuration for Simulated Annealing #
#########################################

random_seed: 42

# Simulated annealing
optimizer:
  num_boosters: 4
  num_simulation_steps: 700
  num_iterations: 60000  # Decrease temperature for `num_iterations`
  temp_initial: 0.06
  temp_final: 1.0e-6
  perturbation_probability_initial: 1.0
  perturbation_probability_final: 0.01
  perturbation_rate_initial: 0.1
  perturbation_rate_final: 0.01
  lib: "numpy"    # Fix.

trainer:
  num_episodes: -1  # -1 for infinite episodes or positive integer.

# Simulation environment 
env:

  friction: 5.0

  gravity: # [m / s^2]
    x: 0.0
    y: -9.81

  domain: # [m]
    x_min: -150.0
    x_max: 150.0
    y_max: 450.0
    y_min: -5.0

  landing_pad:
    position: # [m]
      x: -100.0
      y: 0.0

  landing:
    v_max: # [m / s]
      x: 10.0
      y: -15.0

  booster:
    fixed_rotation: true    # Fix rotation for faster learning.

    stress:
      max_angle: 45  # [deg]
      max_angular_velocity: 90  # [deg / s]

    init:
      position: # [m]
        x: 70.0
        y: 400.0
      linear_velocity: # [m/s]
        x: 0.0
        y: -50.0
      angular_velocity: 0.0   # [deg / s], counterclockwise for positive numbers
      angle: 0.0              # [deg] counterclockwise

    engine:
      main: # Merlin engine
        max_force: 854000.0  # [N] 854 kN at sea level
        max_angle: 15.0  # [deg] Gimbal angle, about ~15 degrees for Falcon 9
      cold_gas:  # Cold gas propulsion system.
        max_force: 50000.0  # [N]
        max_angle: 15.0  # [deg]

    noise:
      # Specifies standard deviation of Gaussian noise added to agents initial state.
      is_activated: true
      # Specifies whether every agent gets the same starting noise: "identical" or "different"
      type: "identical"
      position: # [m]
        x: 20.0
        y: 20.0
      linear_velocity: # [m / s]
        x: 0.0
        y: 5.0
      angular_velocity: 0.0  # [deg / s]
      angle: 0.0  # [deg]

    neural_network: # model
      num_dim_in: 6       # Position, linear velocity, angular velocity, angle.
      num_dim_out: 6      # Predictions of thrust and angle for three engines.
      num_dim_hidden: 64
      num_hidden_layers: 2

framework:
  screen:
    width: 640
    height: 1024
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 0.0001
  screen:
    shift:
      x: -0.5
      y: -0.05
  ppm: 2     # Pixels per meter (zoom)

# Directory to save the frames to create a video.
dirs:
  frames: "frames"

# Save or load pre-trained neural network.
checkpoints:
  load_model: false 
  save_model: false 
  model_path: "weights"
  model_name: ""