# Genetic optimization configuration for BoosterLanding 
random_seed: 192837465

# Directory to save the frames to create a video.
dirs:
  frames: "frames"

# Parameters to save the booster's neural network.
checkpoints:
  load_model: false
  save_model: false
  model_path: "weights"

trainer:
  num_generations: 10000 # not used yet

optimizer:
  num_boosters: 4
  num_max_steps: 1000
  mutation_probability: 0.01
  mutation_rate: 0.01
  lib: "numpy"    # numpy, torch

env: 
  landing:
    v_max: 
      x: 1.0
      y: -10.0

  domain:
    x_min: -80.0
    x_max: 80.0
    y_max: 100.0
    y_min: -20.0

  gravity: 
    x: 0.0
    y: -9.81

  booster:

    init:
      position: 
        x: 0.0
        y: 28.0
      linear_velocity: 
        x: 0.0
        y: 0.0
      angular_velocity: 0.0
      angle: 0.0

    density: 1.0  # Average density of hull.
 
    engine:
      main: # merlin
        density: 1.0  # Average density of engines.
        max_force: 0.0
        # max_angle: 20.0
      coldgas:  # cold gas propulsion system (cgps)
        max_force: 1.0
        # max_angle: 20.0

    noise: 
      position: 
        x: 1.0                       # Standard deviation [m]
        y: 1.0                       # Standard deviation [m]
      linear_velocity: 
        x: 0.0                        # Standard deviation [m / s]
        y: 0.0                        # Standard deviation [m / s]
      angular_velocity: 0.0             # Standard deviation [rad / s]
      angle: 0.0                      # Standard deviation [deg]

    neural_network: # model
      num_dim_in: 6       # Position, linear velocity, angular velocity, angle
      num_dim_out: 3      # Actions for three engines.
      num_dim_hidden: 8
      num_hidden_layers: 2

framework:
  screen:
    width: 640
    height: 1024
  # offset:
  #   x: 0
  #   y: 0
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 1.0
  ppm: 10     # Pixels per meter / zoom