# Genetic optimization configuration for BoosterLanding 
random_seed: 192837465

# Directory to save the frames to create a video.
dirs:
  frames: "frames"

# Parameters to save the booster's neural network.
checkpoints:
  load_model: false
  save_model: false
  model_path: "weights"

# trainer:
#   num_generations: 10000 # not used yet

optimizer:
  num_boosters: 8
  num_max_steps: 1000
  mutation_probability: 0.04
  mutation_rate: 0.04
  lib: "numpy"    # numpy, torch

env: 
  landing:
    v_max: 
      x: 50.0
      y: -50.0

  domain:
    x_min: -200.0
    x_max: 200.0
    y_max: 500.0
    y_min: -10.0

  gravity: 
    x: 0.0
    y: -9.81

  booster:
    fixed_rotation: true    # Fix rotation for faster learning.

    init:
      position: 
        x: 50.0
        y: 300.0
      linear_velocity: 
        x: 0.0
        y: -20.0
      angular_velocity: 0.0
      angle: 0.0

    density: 1.0  # Average density of hull.
 
    engine:
      main: # merlin
        density: 1.0  # Average density of engines.
        max_force: 20000.0
        max_angle: 15.0   # gimbal angle, Falcon 9: ~15 degrees
      cold_gas:  # Cold gas propulsion system.
        max_force: 1000.0
        max_angle: 10.0

    noise:  # TODO: move this to env?
      position: 
        x: 20.0                       # Standard deviation [m]
        y: 20.0                       # Standard deviation [m]
      linear_velocity: 
        x: 0.0                        # Standard deviation [m / s]
        y: 0.0                        # Standard deviation [m / s]
      angular_velocity: 0.0             # Standard deviation [rad / s]
      angle: 0.0                      # Standard deviation [deg]

    neural_network: # model
      num_dim_in: 6       # Position, linear velocity, angular velocity, angle.
      num_dim_out: 6      # Predictions of thrust and angle for three engines.
      num_dim_hidden: 16
      num_hidden_layers: 2

framework:
  screen:
    width: 640
    height: 1024
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 0.01
  screen:
    shift:
      x: -0.5
      y: -0.05
  ppm: 2     # Pixels per meter / zoom