# Genetic optimization configuration for BoosterLanding 
random_seed: 192837461

# Directory to save the frames to create a video.
dirs:
  frames: "frames"

# Parameters to save the booster's neural network.
checkpoints:
  load_model: false
  save_model: false
  model_path: "weights"

# trainer:
#   num_generations: 10000 # not used yet

optimizer:
  num_boosters: 8
  num_max_steps: 600
  mutation_probability: 0.02
  mutation_rate: 0.02
  lib: "numpy"    # numpy, torch

env:

  gravity: # [m / s^2]
    x: 0.0
    y: -9.81

  domain: # [m]
    x_min: -200.0
    x_max: 200.0
    y_max: 500.0
    y_min: -5.0

  landing_pad:
    position: # [m]
      x: -80.0
      y: 0.0

  landing:
    v_max: # [m / s]
      x: 20.0
      y: -20.0

  booster:
    fixed_rotation: true    # Fix rotation for faster learning.

    stress:
      max_angle: 30   # [deg]
      max_angular_velocity: 90    # [deg / s]

    init:
      position: # [m]
        x: 70.0
        y: 450.0
      linear_velocity: # [m/s]
        x: 0.0
        y: -20.0
      angular_velocity: 0.0   # [deg / s], counterclockwise for positive numbers
      angle: 0.0              # [deg] counterclockwise

    engine:
      main: # merlin
        max_force: 800000.0 # [N]   , Merlin: 854 kN at sea level
        max_angle: 25.0   # gimbal angle, Falcon 9: ~15 degrees
      cold_gas:  # Cold gas propulsion system.
        max_force: 0.0
        max_angle: 0.0

    noise:  # TODO: move this to env?
      position: # [m] 
        x: 10.0                       # Standard deviation [m]
        y: 0.0                       # Standard deviation [m]
      linear_velocity: # [m/s]
        x: 0.0                        # Standard deviation [m / s]
        y: 0.0                        # Standard deviation [m / s]
      angular_velocity: 0.0             # Standard deviation [deg / s]
      angle: 0.0                      # Standard deviation [deg]

    neural_network: # model
      num_dim_in: 6       # Position, linear velocity, angular velocity, angle.
      num_dim_out: 6      # Predictions of thrust and angle for three engines.
      num_dim_hidden: 16
      num_hidden_layers: 2

framework:
  screen:
    width: 640
    height: 1024
  target_fps: 60
  velocity_iterations: 10   # Number of iterations to compute next velocity.
  position_iterations: 10   # Number of iterations to compute next position.

renderer:
  scale_force: 0.0001
  screen:
    shift:
      x: -0.5
      y: -0.05
  ppm: 2     # Pixels per meter / zoom